-- MUDRO 021_e2ee_keys.sql
-- Реестр ключей для сквозного шифрования (E2EE) по протоколу X3DH.

-- Публичные ключи идентификации и подписанные пре-ключи пользователей
CREATE TABLE IF NOT EXISTS user_keys (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    identity_key TEXT NOT NULL, -- Public identity key (base64)
    signed_prekey TEXT NOT NULL, -- Public signed prekey (base64)
    prekey_signature TEXT NOT NULL, -- Signature of the signed prekey (base64)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Одноразовые пре-ключи для асинхронного установления сессий
CREATE TABLE IF NOT EXISTS one_time_prekeys (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_id INTEGER NOT NULL, -- Logical ID of the key generated by the client
    public_key TEXT NOT NULL, -- Public key (base64)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, key_id)
);

CREATE INDEX IF NOT EXISTS idx_one_time_prekeys_user_id ON one_time_prekeys(user_id);

-- Расширяем сообщения для хранения зашифрованного типа
ALTER TABLE messages ADD COLUMN IF NOT EXISTS encryption_type TEXT DEFAULT 'none'; -- 'none', 'x3dh-dr'
